// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuixybzydxiwimwfhrgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1aXh5Ynp5ZHhpd2ltd2ZocmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NDEwMTMsImV4cCI6MjA1NDQxNzAxM30.3veQT2IK2PSKam7Velery_B_12kf3oavy4dg5AVroSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);